version: '3.8'

services:
  app_crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app_crawler
    depends_on:
      - mongodb
    networks:
      - my_network

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27020:27017"
    networks:
        - my_network

networks:
  my_network:
    

    
    